### ISSUE TITLE
Don't display

### ISSUE THREAD

**Issue by TomySmit** [riteshgandhi/ng-star-rating#18] opened 2020-02-26 14:36 UTC
Don't display stars, use Chrome last verstion, add webcomponents bundle, No errors, but not visible
![image](https://user-images.githubusercontent.com/16036950/75354688-764cda00-58be-11ea-93fa-91c27019f430.png)

**Comment by riteshgandhi** [comment] 2020-02-27 20:11
> Don't display stars, use Chrome last verstion, add webcomponents bundle, No errors, but not visible
> ![image](https://user-images.githubusercontent.com/16036950/75354688-764cda00-58be-11ea-93fa-91c27019f430.png)

I will test and let you know

**Comment by riteshgandhi** [comment] 2020-03-03 15:39
@TomySmit - I tested on latest version 80.0.3987.122 on Windows
what version of chrome/os do you have? also check if the demo site works

https://ng-starratingdemo.stackblitz.io/

**Comment by IhorVimmi** [comment] 2020-03-05 11:59
same for me

**Comment by rejneesh1** [comment] 2020-03-05 12:38
Yes i also can not see it no errors also

**Comment by riteshgandhi** [comment] 2020-03-05 15:00
> same for me
> Latest Windows and Opera/chrome/firefox browsers
> 
> Project struct:
> modules
> one-module
> components
> any-component -> use ng-star-rating, but it is not visible
> another-module

is it possible to give me sample project that uses ng-starrating and doesn't show up?

**Comment by jhpassion0621** [comment] 2020-03-05 19:53
@riteshgandhi please share your sample code, it doesn't show on Angular 9

**Comment by riteshgandhi** [comment] 2020-03-05 20:33
> @riteshgandhi please share your sample code, it doesn't show on Angular 9

https://stackblitz.com/edit/ng-starratingdemo

**Comment by abhishek-web-dev** [comment] 2020-03-06 09:06
@riteshgandhi Hi, I am trying to use this library ng-starrating in my angular 9 project but I am unable to see "Stars".

**Comment by jhpassion0621** [comment] 2020-03-06 10:26
@rejneesh1 Thanks for your sharing code. It works well but it still doesn't work on my project. I saw your project has only 2 styles and div tag but there are so many styles and size is 0 in my project. 
![Screen Shot 2020-03-06 at 6 25 22 PM](https://user-images.githubusercontent.com/7741402/76075429-ffa78f00-5fd7-11ea-9dec-4fee4d27d763.png)

**Comment by jhpassion0621** [comment] 2020-03-06 10:50
@rejneesh1 when I set total stars as constant like `totalstars='5'` then it won't work but if I set total stars with value like `[totalstars]='5'`, it works. Maybe it has slight issue :D anyway I got its working now. Thank you.

**Comment by riteshgandhi** [comment] 2020-03-06 13:10
> @rejneesh1 when I set total stars as constant like `totalstars='5'` then it won't work but if I set total stars with value like `[totalstars]='5'`, it works. Maybe it has slight issue :D anyway I got its working now. Thank you.

@jhpassion0621 - great thanks. I'll check what the issue is but glad that you found workaround

**Comment by riteshgandhi** [comment] 2020-03-06 13:12
> @riteshgandhi Hi, I am trying to use this library ng-starrating in my angular 9 project but I am unable to see "Stars". but it is working with an angular 8.0.0 version.

@abhishek-web-dev - try setting total stars like this
[totalstars]='5' and let me know. this is the workaround found by @jhpassion0621 ,I'm going to check the code

**Comment by IhorVimmi** [comment] 2020-03-06 15:01
totalstars 5 gives me same result(

**Comment by riteshgandhi** [comment] 2020-03-06 15:22
> totalstars 5 gives me same result(

So you tried like @jhpassion0621 suggested and it did not work? I would really like to see whats going on with your project. It will be great if you can send me sample that has the issue.

[totalstars]='5'

Hope you got ng-starrating demo code from the like I shared before. 

https://stackblitz.com/edit/ng-starratingdemo

**Comment by IhorVimmi** [comment] 2020-03-06 15:32
@riteshgandhi yes i tryed that solutin and didn't got any changes

**Comment by abhishek-web-dev** [comment] 2020-03-06 17:29
@jhpassion0621 Thanks bro, it is working if we write like [totalstars]='5' this.

**Comment by IhorVimmi** [comment] 2020-03-06 17:53
@riteshgandhi sorry my mistake) now it works!

**Comment by riteshgandhi** [comment] 2020-03-06 17:55
> @riteshgandhi sorry my mistake) now it works!

@IhorVimmi glad it worked

**Comment by riteshgandhi** [comment] 2020-03-06 18:21
> Don't display stars, use Chrome last verstion, add webcomponents bundle, No errors, but not visible
> ![image](https://user-images.githubusercontent.com/16036950/75354688-764cda00-58be-11ea-93fa-91c27019f430.png)

@TomySmit - if you are still using ng-starrating and facing the issue of stars not being displayed then try the workaround to use data binding for totalstars property as suggested by @jhpassion0621 

for example, `[totalstars]='5'`

closing this issue as others have confirmed it worked for them. Feel free to reach out to me / open another issue if you get any error

**Closed by riteshgandhi** 2020-03-06 18:21 UTC

**Comment by Luid101** [comment] 2020-05-29 23:38
> > Don't display stars, use Chrome last verstion, add webcomponents bundle, No errors, but not visible
> > ![image](https://user-images.githubusercontent.com/16036950/75354688-764cda00-58be-11ea-93fa-91c27019f430.png)
> 
> @TomySmit - if you are still using ng-starrating and facing the issue of stars not being displayed then try the workaround to use data binding for totalstars property as suggested by @jhpassion0621
> 
> for example, `[totalstars]='5'`
> 
> closing this issue as others have confirmed it worked for them. Feel free to reach out to me / open another issue if you get any error

can you also update the demos getting started page to use that workaround?
That way it will work for everyone.
